modLoader = "kotlinforforge"
loaderVersion = "[${forge_kotlin_version},)"
issueTrackerURL = "${issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "nbt_to_vs"
version = "${1.20.1}"
displayName = "${NBTtoVS}"
displayURL = "${homepage}"
authors = ["${Brokyle22, CommunistFox}"]
description = '''
${For Warium, cause Novum asked us}
'''
logoFile = "icon.png"

[[dependencies.nbt_to_vs]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nbt_to_vs]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nbt_to_vs]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.nbt_to_vs]]
modId="kotlinforforge"
mandatory=true
versionRange="[${forge_kotlin_version},)"
ordering="BEFORE"
side="BOTH"


