modLoader = "kotlinforforge"
loaderVersion = "[47.2.0,)"
issueTrackerURL = ""
license = "Apache 2.0"

[[mods]]
modId = "nbt_to_vs"
version = "1.20.1"
displayName = "NBTtoVS"
displayURL = "Can't be bothered"
authors = ["Brokyle22, CommunistFox"]
description = '''
For a buddy
'''
logoFile = "icon.png"

[[dependencies.nbt_to_vs]]
modId = "forge"
mandatory = true
versionRange = "[47.3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nbt_to_vs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nbt_to_vs]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.3.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.nbt_to_vs]]
modId="kotlinforforge"
mandatory=true
versionRange="[4.11.0,)"
ordering="BEFORE"
side="BOTH"
